# Generated by Django 6.0 on 2025-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_unit', models.CharField(max_length=50)),
                ('emp_dept', models.CharField(max_length=50)),
                ('emp_desgination', models.CharField(max_length=50)),
                ('emp_manager', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=50)),
                ('emp_phone', models.CharField(max_length=50)),
                ('emp_dob', models.DateField(max_length=50)),
                ('emp_doj', models.DateField(max_length=50)),
                ('emp_dor', models.DateField(blank=True, null=True)),
                ('emp_status', models.CharField(max_length=50)),
            ],
        ),
    ]
