# Generated by Django 6.0 on 2025-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('tk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tk_unit', models.CharField(max_length=15)),
                ('tk_category', models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('AD', 'Administrative')], max_length=2, verbose_name='Ticket Category')),
                ('tk_type', models.CharField(choices=[('DE', 'Defect'), ('NE', 'New'), ('TR', 'Training'), ('DC', 'Data Correction'), ('TS', 'Hardware Support'), ('RM', 'Roadmap Support'), ('SU', 'Stock Update'), ('BI', 'Billing Inquiry'), ('FE', 'Feature Request'), ('OT', 'Other')], max_length=2, verbose_name='Ticket Type')),
                ('tk_priority', models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('AD', 'Administrative')], max_length=2, verbose_name='Ticket Priority')),
                ('tk_menu', models.CharField(max_length=25)),
                ('tk_req_by', models.CharField(max_length=150)),
                ('tk_req_phone', models.CharField(blank=True, help_text='Optional contact number, including country code (e.g., +1 555-123-4567).', max_length=20, verbose_name='Contact Phone')),
                ('tk_req_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email (Optional)')),
                ('tk_subject', models.CharField(max_length=250)),
                ('tk_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('tk_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('tk_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
