# Generated by Django 6.0 on 2025-12-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tk_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tk_category',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software')], max_length=2, verbose_name='Ticket Category'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tk_priority',
            field=models.CharField(choices=[('CR', 'Critical'), ('HH', 'High'), ('MD', 'Medium'), ('LW', 'Low')], max_length=2, verbose_name='Ticket Priority'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tk_type',
            field=models.CharField(choices=[('DE', 'Defect'), ('NE', 'New Request'), ('TR', 'Training'), ('DC', 'Data Correction'), ('TS', 'Hardware Support'), ('RM', 'Roadmap Support'), ('SU', 'Stock Update'), ('BI', 'Billing Inquiry'), ('FE', 'Feature Request'), ('OT', 'Other'), ('PF', 'Physical Failure'), ('PD', 'Peripheral Devices'), ('IN', 'Installation Setup'), ('UP', 'Upgrade'), ('CI', 'Connectivity Problem'), ('DI', 'Diagnosis Inspection')], max_length=2, verbose_name='Ticket Type'),
        ),
    ]
