# Generated by Django 6.0 on 2025-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_tk_description_alter_tickets_tk_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tk_assigned',
            field=models.CharField(choices=[('KRB', 'Ranjith'), ('SSR', 'Saran'), ('GSR', 'Gowri')], max_length=3, null=True, verbose_name='Ticket Assigned'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Inprogress'), ('A', 'Assigned'), ('C', 'Completed'), ('R', 'Reopen')], default='P', max_length=2, null=True, verbose_name='Ticket Status'),
        ),
    ]
