# Generated by Django 6.0 on 2025-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickets_tk_assigned_tickets_tk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tk_corrective_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_dept',
            field=models.CharField(max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('NR', 'New Report'), ('BE', 'Backend'), ('IH', 'Inhouse'), ('TR', 'Training'), ('RP', 'Repeated'), ('DC', 'Data Correction'), ('FE', 'Frontend')], max_length=2, null=True, verbose_name='Error Classification'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_incident_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Incident date'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_preventive_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_rm_assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_rm_dt',
            field=models.DateField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_rm_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_rm_status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Inprogress'), ('A', 'Assigned'), ('C', 'Completed'), ('R', 'Reopen')], default='P', max_length=2, null=True, verbose_name='Ticket Status'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_root_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tk_scrn_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
