# Generated by Django 6.0 on 2025-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_tickets_tk_corrective_action_tickets_tk_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets_check',
            fields=[
                ('tk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tk_powerapps_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tk_rm_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RMIT Ticket No')),
                ('tk_unit', models.CharField(max_length=100)),
                ('tk_dept', models.CharField(max_length=100, null=True, verbose_name='Department')),
                ('tk_menu', models.CharField(max_length=255)),
                ('tk_scrn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tk_subject', models.CharField(max_length=250)),
                ('tk_description', models.TextField(blank=True, null=True)),
                ('tk_category', models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software')], default='SW', max_length=2)),
                ('tk_type', models.CharField(choices=[('DE', 'Defect'), ('NE', 'New Request'), ('TR', 'Training'), ('DC', 'Data Correction'), ('TS', 'Hardware Support'), ('RM', 'Roadmap Support'), ('SU', 'Stock Update'), ('BI', 'Billing Inquiry'), ('FE', 'Feature Request'), ('OT', 'Other'), ('PF', 'Physical Failure'), ('PD', 'Peripheral Devices'), ('IN', 'Installation Setup'), ('UP', 'Upgrade'), ('CI', 'Connectivity Problem'), ('DI', 'Diagnosis Inspection')], default='OT', max_length=2)),
                ('tk_req_by', models.CharField(max_length=150)),
                ('tk_req_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('tk_req_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tk_incident_dt', models.DateField(blank=True, null=True, verbose_name='Incident date')),
                ('tk_rm_dt', models.DateField(blank=True, null=True, verbose_name='RMIT Ticket Date')),
                ('tk_created_at', models.DateTimeField(auto_now_add=True)),
                ('tk_updated_at', models.DateTimeField(auto_now=True)),
                ('tk_closure_time', models.DateTimeField(blank=True, null=True)),
                ('tk_time_diff', models.FloatField(blank=True, null=True)),
                ('tk_priority', models.CharField(choices=[('CR', 'Critical'), ('HH', 'High'), ('MD', 'Medium'), ('LW', 'Low')], max_length=2)),
                ('tk_status', models.CharField(choices=[('P', 'Pending'), ('I', 'Inprogress'), ('A', 'Assigned'), ('C', 'Completed'), ('R', 'Reopen')], default='P', max_length=2)),
                ('tk_rm_status', models.CharField(blank=True, choices=[('P', 'Pending'), ('I', 'Inprogress'), ('A', 'Assigned'), ('C', 'Completed'), ('R', 'Reopen')], max_length=2, null=True)),
                ('tk_err_class', models.CharField(blank=True, choices=[('NR', 'New Report'), ('FE', 'Frontend'), ('IH', 'Inhouse'), ('BE', 'Backend'), ('RP', 'Repeated'), ('TR', 'Training'), ('DC', 'Data Correction')], max_length=2, null=True)),
                ('tk_assigned', models.CharField(choices=[('KRB', 'Ranjith'), ('SSR', 'Saran'), ('GSR', 'Gowri')], max_length=3, null=True)),
                ('tk_handled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tk_root_cause', models.TextField(blank=True, null=True)),
                ('tk_corrective_action', models.TextField(blank=True, null=True)),
                ('tk_preventive_action', models.TextField(blank=True, null=True)),
                ('tk_mail_send_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-tk_created_at'],
            },
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('NR', 'New Report'), ('FE', 'Frontend'), ('IH', 'Inhouse'), ('BE', 'Backend'), ('RP', 'Repeated'), ('TR', 'Training'), ('DC', 'Data Correction')], max_length=2, null=True, verbose_name='Error Classification'),
        ),
    ]
