# Generated by Django 6.0 on 2025-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tickets_check_alter_tickets_tk_err_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('TR', 'Training'), ('IH', 'Inhouse'), ('DC', 'Data Correction'), ('BE', 'Backend'), ('FE', 'Frontend'), ('NR', 'New Report'), ('RP', 'Repeated')], max_length=2, null=True, verbose_name='Error Classification'),
        ),
        migrations.AlterField(
            model_name='tickets_check',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('TR', 'Training'), ('IH', 'Inhouse'), ('DC', 'Data Correction'), ('BE', 'Backend'), ('FE', 'Frontend'), ('NR', 'New Report'), ('RP', 'Repeated')], max_length=2, null=True),
        ),
    ]
