# Generated by Django 6.0 on 2025-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_tickets_tk_err_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('NR', 'New Report'), ('IH', 'Inhouse'), ('TR', 'Training'), ('RP', 'Repeated'), ('DC', 'Data Correction'), ('FE', 'Frontend'), ('BE', 'Backend')], max_length=2, null=True, verbose_name='Error Classification'),
        ),
        migrations.AlterField(
            model_name='tickets_check',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('NR', 'New Report'), ('IH', 'Inhouse'), ('TR', 'Training'), ('RP', 'Repeated'), ('DC', 'Data Correction'), ('FE', 'Frontend'), ('BE', 'Backend')], max_length=2, null=True),
        ),
    ]
