# Generated by Django 6.0 on 2025-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_tickets_tk_err_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets_check',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('BE', 'Backend'), ('FE', 'Frontend'), ('DC', 'Data Correction'), ('NR', 'New Report'), ('RP', 'Repeated'), ('TR', 'Training'), ('IH', 'Inhouse')], max_length=2, null=True, verbose_name='Error Classification'),
        ),
    ]
