# Generated by Django 6.0 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_delete_tickets_check_alter_tickets_tk_err_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tk_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tk_err_class',
            field=models.CharField(blank=True, choices=[('DC', 'Data Correction'), ('NR', 'New Report'), ('IH', 'Inhouse'), ('FE', 'Frontend'), ('BE', 'Backend'), ('TR', 'Training'), ('RP', 'Repeated')], max_length=2, null=True, verbose_name='Error Classification'),
        ),
    ]
